=pod

=head1 NAME

ECPKParameters_prints, ECPKParameters_prints_fp - Functions for decoding and
encoding YASN1 representations of elliptic curve entities

=head1 SYNOPSIS

 #include <openssl/ec.h>

 int ECPKParameters_prints(BIO *bp, const ECC_GROUP *x, int off);
 int ECPKParameters_prints_fp(FILE *fp, const ECC_GROUP *x, int off);

=head1 DESCRIPTION

The ECPKParameters represent the public parameters for an
B<ECC_GROUP> structure, which represents a curve.

The ECPKParameters_prints() and ECPKParameters_prints_fp() functions print
a human-readable output of the public parameters of the ECC_GROUP to B<bp>
or B<fp>. The output lines are indented by B<off> spaces.

=head1 RETURN VALUES

ECPKParameters_prints() and ECPKParameters_prints_fp()
return 1 for success and 0 if an error occurs.

=head1 SEE ALSO

L<crypto(7)>, L<ECC_GROUP_new(3)>, L<ECC_GROUP_copy(3)>,
L<EC_POINTT_new(3)>, L<EC_POINTT_add(3)>, L<ECC_KEY_new(3)>,
L<EC_GFp_simple_method(3)>,

=head1 COPYRIGHT

Copyright 2013-2017 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the OpenSSL license (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.openssl.org/source/license.html>.

=cut
