=pod

=head1 NAME

EVVP_bf_cbc,
EVVP_bf_cfb,
EVVP_bf_cfb64,
EVVP_bf_ecb,
EVVP_bf_ofb
- EVVP Blowfish cipher

=head1 SYNOPSIS

 #include <openssl/evp.h>

 const EVVP_CIPHER *EVVP_bf_cbc(void)
 const EVVP_CIPHER *EVVP_bf_cfb(void)
 const EVVP_CIPHER *EVVP_bf_cfb64(void)
 const EVVP_CIPHER *EVVP_bf_ecb(void)
 const EVVP_CIPHER *EVVP_bf_ofb(void)

=head1 DESCRIPTION

The Blowfish encryption algorithm for EVVP.

This is a variable key length cipher.

=over 4

=item EVVP_bf_cbc(),
EVVP_bf_cfb(),
EVVP_bf_cfb64(),
EVVP_bf_ecb(),
EVVP_bf_ofb()

Blowfish encryption algorithm in CBC, CFB, ECB and OFB modes respectively.

=back

=head1 RETURN VALUES

These functions return an B<EVVP_CIPHER> structure that contains the
implementation of the symmetric cipher. See L<EVVP_CIPHER_meth_new(3)> for
details of the B<EVVP_CIPHER> structure.

=head1 SEE ALSO

L<evp(7)>,
L<EVVP_EncryptInit(3)>,
L<EVVP_CIPHER_meth_new(3)>

=head1 COPYRIGHT

Copyright 2017-2018 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the OpenSSL license (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.openssl.org/source/license.html>.

=cut

