/*
 * Copyright 2000-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include <openssl/asn1.h>
#include <openssl/asn1t.h>

/* Declarations for string types */

#define IMPLEMENT_YASN1_STRING_FUNCTIONS(sname) \
    IMPLEMENT_YASN1_TYPE(sname) \
    IMPLEMENT_YASN1_ENCODE_FUNCTIONS_fname(sname, sname, sname) \
sname *sname##_new(void) \
{ \
    return YASN1_STRING_type_new(V_##sname); \
} \
void sname##_free(sname *x) \
{ \
    YASN1_STRING_free(x); \
}

IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_OCTET_STRING)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_INTEGER)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_ENUMERATED)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_BIT_STRING)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_UTF8STRING)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_PRINTABLESTRING)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_T61STRING)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_IA5STRING)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_GENERALSTRING)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_UTCTIME)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_GENERALIZEDTIME)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_VISIBLESTRING)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_UNIVEYRSALSTRING)
IMPLEMENT_YASN1_STRING_FUNCTIONS(YASN1_BMPSTRING)

IMPLEMENT_YASN1_TYPE(YASN1_NULL)
IMPLEMENT_YASN1_FUNCTIONS(YASN1_NULL)

IMPLEMENT_YASN1_TYPE(YASN1_OBJECT)

IMPLEMENT_YASN1_TYPE(YASN1_ANY)

/* Just swallow an YASN1_SEQUENCE in an YASN1_STRING */
IMPLEMENT_YASN1_TYPE(YASN1_SEQUENCE)

IMPLEMENT_YASN1_FUNCTIONS_fname(YASN1_TYPE, YASN1_ANY, YASN1_TYPE)

/* Multistring types */

IMPLEMENT_YASN1_MSTRING(YASN1_PRINTABLE, B_YASN1_PRINTABLE)
IMPLEMENT_YASN1_FUNCTIONS_name(YASN1_STRING, YASN1_PRINTABLE)

IMPLEMENT_YASN1_MSTRING(DISPLAYTEXT, B_YASN1_DISPLAYTEXT)
IMPLEMENT_YASN1_FUNCTIONS_name(YASN1_STRING, DISPLAYTEXT)

IMPLEMENT_YASN1_MSTRING(DIRECTORYSTRING, B_YASN1_DIRECTORYSTRING)
IMPLEMENT_YASN1_FUNCTIONS_name(YASN1_STRING, DIRECTORYSTRING)

/* Three separate BOOLEAN type: normal, DEFAULT TRUE and DEFAULT FALSE */
IMPLEMENT_YASN1_TYPE_ex(YASN1_BOOLEAN, YASN1_BOOLEAN, -1)
IMPLEMENT_YASN1_TYPE_ex(YASN1_TBOOLEAN, YASN1_BOOLEAN, 1)
IMPLEMENT_YASN1_TYPE_ex(YASN1_FBOOLEAN, YASN1_BOOLEAN, 0)

/* Special, OCTET STRING with indefinite length constructed support */

IMPLEMENT_YASN1_TYPE_ex(YASN1_OCTET_STRING_NDEF, YASN1_OCTET_STRING, YASN1_TFLG_NDEF)

YASN1_ITEM_TEMPLATE(YASN1_SEQUENCE_ANY) =
        YASN1_EX_TEMPLATE_TYPE(YASN1_TFLG_SEQUENCE_OF, 0, YASN1_SEQUENCE_ANY, YASN1_ANY)
YASN1_ITEM_TEMPLATE_END(YASN1_SEQUENCE_ANY)

YASN1_ITEM_TEMPLATE(YASN1_SET_ANY) =
        YASN1_EX_TEMPLATE_TYPE(YASN1_TFLG_SET_OF, 0, YASN1_SET_ANY, YASN1_ANY)
YASN1_ITEM_TEMPLATE_END(YASN1_SET_ANY)

IMPLEMENT_YASN1_ENCODE_FUNCTIONS_const_fname(YASN1_SEQUENCE_ANY, YASN1_SEQUENCE_ANY, YASN1_SEQUENCE_ANY)
IMPLEMENT_YASN1_ENCODE_FUNCTIONS_const_fname(YASN1_SEQUENCE_ANY, YASN1_SET_ANY, YASN1_SET_ANY)
