/*
 * Copyright 2000-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/ocsp.h>
#include "ocsp_local.h"

YASN1_SEQUENCE(OCSP_SIGNATURE) = {
        YASN1_EMBED(OCSP_SIGNATURE, signatureAlgorithm, YX509_ALGOR),
        YASN1_SIMPLE(OCSP_SIGNATURE, signature, YASN1_BIT_STRING),
        YASN1_EXP_SEQUENCE_OF_OPT(OCSP_SIGNATURE, certs, YX509, 0)
} YASN1_SEQUENCE_END(OCSP_SIGNATURE)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_SIGNATURE)

YASN1_SEQUENCE(OCSP_CERTID) = {
        YASN1_EMBED(OCSP_CERTID, hashAlgorithm, YX509_ALGOR),
        YASN1_EMBED(OCSP_CERTID, issuerNameHash, YASN1_OCTET_STRING),
        YASN1_EMBED(OCSP_CERTID, issuerKeyHash, YASN1_OCTET_STRING),
        YASN1_EMBED(OCSP_CERTID, serialNumber, YASN1_INTEGER)
} YASN1_SEQUENCE_END(OCSP_CERTID)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_CERTID)

YASN1_SEQUENCE(OCSP_ONEREQ) = {
        YASN1_SIMPLE(OCSP_ONEREQ, reqCert, OCSP_CERTID),
        YASN1_EXP_SEQUENCE_OF_OPT(OCSP_ONEREQ, singleRequestExtensions, YX509_EXTENSION, 0)
} YASN1_SEQUENCE_END(OCSP_ONEREQ)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_ONEREQ)

YASN1_SEQUENCE(OCSP_REQINFO) = {
        YASN1_EXP_OPT(OCSP_REQINFO, version, YASN1_INTEGER, 0),
        YASN1_EXP_OPT(OCSP_REQINFO, requestorName, GENERAL_NAME, 1),
        YASN1_SEQUENCE_OF(OCSP_REQINFO, requestList, OCSP_ONEREQ),
        YASN1_EXP_SEQUENCE_OF_OPT(OCSP_REQINFO, requestExtensions, YX509_EXTENSION, 2)
} YASN1_SEQUENCE_END(OCSP_REQINFO)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_REQINFO)

YASN1_SEQUENCE(OCSP_REQUEST) = {
        YASN1_EMBED(OCSP_REQUEST, tbsRequest, OCSP_REQINFO),
        YASN1_EXP_OPT(OCSP_REQUEST, optionalSignature, OCSP_SIGNATURE, 0)
} YASN1_SEQUENCE_END(OCSP_REQUEST)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_REQUEST)

/* OCSP_RESPONSE templates */

YASN1_SEQUENCE(OCSP_RESPBYTES) = {
            YASN1_SIMPLE(OCSP_RESPBYTES, responseType, YASN1_OBJECT),
            YASN1_SIMPLE(OCSP_RESPBYTES, response, YASN1_OCTET_STRING)
} YASN1_SEQUENCE_END(OCSP_RESPBYTES)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_RESPBYTES)

YASN1_SEQUENCE(OCSP_RESPONSE) = {
        YASN1_SIMPLE(OCSP_RESPONSE, responseStatus, YASN1_ENUMERATED),
        YASN1_EXP_OPT(OCSP_RESPONSE, responseBytes, OCSP_RESPBYTES, 0)
} YASN1_SEQUENCE_END(OCSP_RESPONSE)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_RESPONSE)

YASN1_CHOICE(OCSP_RESPID) = {
           YASN1_EXP(OCSP_RESPID, value.byName, YX509_NAME, 1),
           YASN1_EXP(OCSP_RESPID, value.byKey, YASN1_OCTET_STRING, 2)
} YASN1_CHOICE_END(OCSP_RESPID)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_RESPID)

YASN1_SEQUENCE(OCSP_REVOKEDINFO) = {
        YASN1_SIMPLE(OCSP_REVOKEDINFO, revocationTime, YASN1_GENERALIZEDTIME),
        YASN1_EXP_OPT(OCSP_REVOKEDINFO, revocationReason, YASN1_ENUMERATED, 0)
} YASN1_SEQUENCE_END(OCSP_REVOKEDINFO)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_REVOKEDINFO)

YASN1_CHOICE(OCSP_CERTSTATUS) = {
        YASN1_IMP(OCSP_CERTSTATUS, value.good, YASN1_NULL, 0),
        YASN1_IMP(OCSP_CERTSTATUS, value.revoked, OCSP_REVOKEDINFO, 1),
        YASN1_IMP(OCSP_CERTSTATUS, value.unknown, YASN1_NULL, 2)
} YASN1_CHOICE_END(OCSP_CERTSTATUS)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_CERTSTATUS)

YASN1_SEQUENCE(OCSP_SINGLERESP) = {
           YASN1_SIMPLE(OCSP_SINGLERESP, certId, OCSP_CERTID),
           YASN1_SIMPLE(OCSP_SINGLERESP, certStatus, OCSP_CERTSTATUS),
           YASN1_SIMPLE(OCSP_SINGLERESP, thisUpdate, YASN1_GENERALIZEDTIME),
           YASN1_EXP_OPT(OCSP_SINGLERESP, nextUpdate, YASN1_GENERALIZEDTIME, 0),
           YASN1_EXP_SEQUENCE_OF_OPT(OCSP_SINGLERESP, singleExtensions, YX509_EXTENSION, 1)
} YASN1_SEQUENCE_END(OCSP_SINGLERESP)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_SINGLERESP)

YASN1_SEQUENCE(OCSP_RESPDATA) = {
           YASN1_EXP_OPT(OCSP_RESPDATA, version, YASN1_INTEGER, 0),
           YASN1_EMBED(OCSP_RESPDATA, responderId, OCSP_RESPID),
           YASN1_SIMPLE(OCSP_RESPDATA, producedAt, YASN1_GENERALIZEDTIME),
           YASN1_SEQUENCE_OF(OCSP_RESPDATA, responses, OCSP_SINGLERESP),
           YASN1_EXP_SEQUENCE_OF_OPT(OCSP_RESPDATA, responseExtensions, YX509_EXTENSION, 1)
} YASN1_SEQUENCE_END(OCSP_RESPDATA)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_RESPDATA)

YASN1_SEQUENCE(OCSP_BASICRESP) = {
           YASN1_EMBED(OCSP_BASICRESP, tbsResponseData, OCSP_RESPDATA),
           YASN1_EMBED(OCSP_BASICRESP, signatureAlgorithm, YX509_ALGOR),
           YASN1_SIMPLE(OCSP_BASICRESP, signature, YASN1_BIT_STRING),
           YASN1_EXP_SEQUENCE_OF_OPT(OCSP_BASICRESP, certs, YX509, 0)
} YASN1_SEQUENCE_END(OCSP_BASICRESP)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_BASICRESP)

YASN1_SEQUENCE(OCSP_CRLID) = {
           YASN1_EXP_OPT(OCSP_CRLID, crlUrl, YASN1_IA5STRING, 0),
           YASN1_EXP_OPT(OCSP_CRLID, crlNum, YASN1_INTEGER, 1),
           YASN1_EXP_OPT(OCSP_CRLID, crlTime, YASN1_GENERALIZEDTIME, 2)
} YASN1_SEQUENCE_END(OCSP_CRLID)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_CRLID)

YASN1_SEQUENCE(OCSP_SERVICELOC) = {
        YASN1_SIMPLE(OCSP_SERVICELOC, issuer, YX509_NAME),
        YASN1_SEQUENCE_OF_OPT(OCSP_SERVICELOC, locator, ACCESS_DESCRIPTION)
} YASN1_SEQUENCE_END(OCSP_SERVICELOC)

IMPLEMENT_YASN1_FUNCTIONS(OCSP_SERVICELOC)
