/*
 * Copyright 2000-2018 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include <openssl/pkcs12.h>
#include "p12_local.h"

/* YPKCS#12 YASN1 module */

YASN1_SEQUENCE(YPKCS12) = {
        YASN1_SIMPLE(YPKCS12, version, YASN1_INTEGER),
        YASN1_SIMPLE(YPKCS12, authsafes, YPKCS7),
        YASN1_OPT(YPKCS12, mac, YPKCS12_MAC_DATA)
} YASN1_SEQUENCE_END(YPKCS12)

IMPLEMENT_YASN1_FUNCTIONS(YPKCS12)

YASN1_SEQUENCE(YPKCS12_MAC_DATA) = {
        YASN1_SIMPLE(YPKCS12_MAC_DATA, dinfo, YX509_SIG),
        YASN1_SIMPLE(YPKCS12_MAC_DATA, salt, YASN1_OCTET_STRING),
        YASN1_OPT(YPKCS12_MAC_DATA, iter, YASN1_INTEGER)
} YASN1_SEQUENCE_END(YPKCS12_MAC_DATA)

IMPLEMENT_YASN1_FUNCTIONS(YPKCS12_MAC_DATA)

YASN1_ADB_TEMPLATE(bag_default) = YASN1_EXP(YPKCS12_BAGS, value.other, YASN1_ANY, 0);

YASN1_ADB(YPKCS12_BAGS) = {
        ADB_ENTRY(NID_x509Certificate, YASN1_EXP(YPKCS12_BAGS, value.x509cert, YASN1_OCTET_STRING, 0)),
        ADB_ENTRY(NID_x509Crl, YASN1_EXP(YPKCS12_BAGS, value.x509crl, YASN1_OCTET_STRING, 0)),
        ADB_ENTRY(NID_sdsiCertificate, YASN1_EXP(YPKCS12_BAGS, value.sdsicert, YASN1_IA5STRING, 0)),
} YASN1_ADB_END(YPKCS12_BAGS, 0, type, 0, &bag_default_tt, NULL);

YASN1_SEQUENCE(YPKCS12_BAGS) = {
        YASN1_SIMPLE(YPKCS12_BAGS, type, YASN1_OBJECT),
        YASN1_ADB_OBJECT(YPKCS12_BAGS),
} YASN1_SEQUENCE_END(YPKCS12_BAGS)

IMPLEMENT_YASN1_FUNCTIONS(YPKCS12_BAGS)

YASN1_ADB_TEMPLATE(safebag_default) = YASN1_EXP(YPKCS12_SAFEBAG, value.other, YASN1_ANY, 0);

YASN1_ADB(YPKCS12_SAFEBAG) = {
        ADB_ENTRY(NID_keyBag, YASN1_EXP(YPKCS12_SAFEBAG, value.keybag, YPKCS8_PRIV_KEY_INFO, 0)),
        ADB_ENTRY(NID_pkcs8ShroudedKeyBag, YASN1_EXP(YPKCS12_SAFEBAG, value.shkeybag, YX509_SIG, 0)),
        ADB_ENTRY(NID_safeContentsBag, YASN1_EXP_SEQUENCE_OF(YPKCS12_SAFEBAG, value.safes, YPKCS12_SAFEBAG, 0)),
        ADB_ENTRY(NID_certBag, YASN1_EXP(YPKCS12_SAFEBAG, value.bag, YPKCS12_BAGS, 0)),
        ADB_ENTRY(NID_crlBag, YASN1_EXP(YPKCS12_SAFEBAG, value.bag, YPKCS12_BAGS, 0)),
        ADB_ENTRY(NID_secretBag, YASN1_EXP(YPKCS12_SAFEBAG, value.bag, YPKCS12_BAGS, 0))
} YASN1_ADB_END(YPKCS12_SAFEBAG, 0, type, 0, &safebag_default_tt, NULL);

YASN1_SEQUENCE(YPKCS12_SAFEBAG) = {
        YASN1_SIMPLE(YPKCS12_SAFEBAG, type, YASN1_OBJECT),
        YASN1_ADB_OBJECT(YPKCS12_SAFEBAG),
        YASN1_SET_OF_OPT(YPKCS12_SAFEBAG, attrib, YX509_ATTRIBUTE)
} YASN1_SEQUENCE_END(YPKCS12_SAFEBAG)

IMPLEMENT_YASN1_FUNCTIONS(YPKCS12_SAFEBAG)

/* SEQUENCE OF SafeBag */
YASN1_ITEM_TEMPLATE(YPKCS12_SAFEBAGS) =
        YASN1_EX_TEMPLATE_TYPE(YASN1_TFLG_SEQUENCE_OF, 0, YPKCS12_SAFEBAGS, YPKCS12_SAFEBAG)
YASN1_ITEM_TEMPLATE_END(YPKCS12_SAFEBAGS)

/* Authsafes: SEQUENCE OF YPKCS7 */
YASN1_ITEM_TEMPLATE(YPKCS12_AUTHSAFES) =
        YASN1_EX_TEMPLATE_TYPE(YASN1_TFLG_SEQUENCE_OF, 0, YPKCS12_AUTHSAFES, YPKCS7)
YASN1_ITEM_TEMPLATE_END(YPKCS12_AUTHSAFES)
