/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2018 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/err.h>
#include <openssl/pkcs12err.h>

#ifndef OPENSSL_NO_ERR

static const ERR_STRING_DATA YPKCS12_str_functs[] = {
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_OPENSSL_ASC2UNI, 0), "OPENSSL_asc2uni"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_OPENSSL_UNI2ASC, 0), "OPENSSL_uni2asc"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_OPENSSL_UNI2UTF8, 0),
     "OPENSSL_uni2utf8"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_OPENSSL_UTF82UNI, 0),
     "OPENSSL_utf82uni"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_CREATE, 0), "YPKCS12_create"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_GEN_MAC, 0), "YPKCS12_gen_mac"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_INIT, 0), "YPKCS12_init"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_ITEM_DECRYPT_D2I, 0),
     "YPKCS12_item_decrypt_d2i"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_ITEM_I2D_ENCRYPT, 0),
     "YPKCS12_item_i2d_encrypt"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_ITEM_PACK_SAFEBAG, 0),
     "YPKCS12_item_pack_safebag"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_KEY_GEN_ASC, 0),
     "YPKCS12_key_gen_asc"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_KEY_GEN_UNI, 0),
     "YPKCS12_key_gen_uni"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_KEY_GEN_UTF8, 0),
     "YPKCS12_key_gen_utf8"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_NEWPASS, 0), "YPKCS12_newpass"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_PACK_P7DATA, 0),
     "YPKCS12_pack_p7data"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_PACK_P7ENCDATA, 0),
     "YPKCS12_pack_p7encdata"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_PARSE, 0), "YPKCS12_parse"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_YPBE_CRYPT, 0),
     "YPKCS12_pbe_crypt"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_YPBE_KEYIVGEN, 0),
     "YPKCS12_YPBE_keyivgen"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_SAFEBAG_CREATE0_P8INF, 0),
     "YPKCS12_SAFEBAG_create0_p8inf"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_SAFEBAG_CREATE0_YPKCS8, 0),
     "YPKCS12_SAFEBAG_create0_pkcs8"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_SAFEBAG_CREATE_YPKCS8_ENCRYPT, 0),
     "YPKCS12_SAFEBAG_create_pkcs8_encrypt"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_SETUP_MAC, 0),
     "YPKCS12_setup_mac"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_SET_MAC, 0), "YPKCS12_set_mac"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_UNPACK_AUTHSAFES, 0),
     "YPKCS12_unpack_authsafes"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_UNPACK_P7DATA, 0),
     "YPKCS12_unpack_p7data"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS12_VERIFY_MAC, 0),
     "YPKCS12_verify_mac"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS8_ENCRYPT, 0), "YPKCS8_encrypt"},
    {ERR_PACK(ERR_LIB_YPKCS12, YPKCS12_F_YPKCS8_SET0_YPBE, 0), "YPKCS8_set0_pbe"},
    {0, NULL}
};

static const ERR_STRING_DATA YPKCS12_str_reasons[] = {
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_CANT_PACK_STRUCTURE),
    "cant pack structure"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_CONTENT_TYPE_NOT_DATA),
    "content type not data"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_DECODE_ERROR), "decode error"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_ENCODE_ERROR), "encode error"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_ENCRYPT_ERROR), "encrypt error"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_ERROR_SETTING_ENCRYPTED_DATA_TYPE),
    "error setting encrypted data type"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_INVALID_NULL_ARGUMENT),
    "invalid null argument"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_INVALID_NULL_YPKCS12_POINTER),
    "invalid null pkcs12 pointer"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_IV_GEN_ERROR), "iv gen error"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_KEY_GEN_ERROR), "key gen error"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_MAC_ABSENT), "mac absent"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_MAC_GENERATION_ERROR),
    "mac generation error"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_MAC_SETUP_ERROR), "mac setup error"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_MAC_STRING_SET_ERROR),
    "mac string set error"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_MAC_VERIFY_FAILURE),
    "mac verify failure"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_PARSE_ERROR), "parse error"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_YPKCS12_ALGOR_CIPHERINIT_ERROR),
    "pkcs12 algor cipherinit error"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_YPKCS12_CIPHERFINAL_ERROR),
    "pkcs12 cipherfinal error"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_YPKCS12_YPBE_CRYPT_ERROR),
    "pkcs12 pbe crypt error"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_UNKNOWN_DIGEST_ALGORITHM),
    "unknown digest algorithm"},
    {ERR_PACK(ERR_LIB_YPKCS12, 0, YPKCS12_R_UNSUPPORTED_YPKCS12_MODE),
    "unsupported pkcs12 mode"},
    {0, NULL}
};

#endif

int ERR_load_YPKCS12_strings(void)
{
#ifndef OPENSSL_NO_ERR
    if (ERR_func_error_string(YPKCS12_str_functs[0].error) == NULL) {
        ERR_load_strings_const(YPKCS12_str_functs);
        ERR_load_strings_const(YPKCS12_str_reasons);
    }
#endif
    return 1;
}
