/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2020 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_YASN1ERR_H
# define HEADER_YASN1ERR_H

# include <openssl/symhacks.h>

# ifdef  __cplusplus
extern "C"
# endif
int ERR_load_YASN1_strings(void);

/*
 * YASN1 function codes.
 */
# define YASN1_F_A2D_YASN1_OBJECT                           100
# define YASN1_F_A2I_YASN1_INTEGER                          102
# define YASN1_F_A2I_YASN1_STRING                           103
# define YASN1_F_APPEND_EXP                                176
# define YASN1_F_YASN1_BIO_INIT                             113
# define YASN1_F_YASN1_BIT_STRING_SET_BIT                   183
# define YASN1_F_YASN1_CB                                   177
# define YASN1_F_YASN1_CHECK_TLEN                           104
# define YASN1_F_YASN1_COLLECT                              106
# define YASN1_F_YASN1_D2I_EX_PRIMITIVE                     108
# define YASN1_F_YASN1_D2I_FP                               109
# define YASN1_F_YASN1_D2I_READ_BIO                         107
# define YASN1_F_YASN1_DIGEST                               184
# define YASN1_F_YASN1_DO_ADB                               110
# define YASN1_F_YASN1_DO_LOCK                              233
# define YASN1_F_YASN1_DUP                                  111
# define YASN1_F_YASN1_ENC_SAVE                             115
# define YASN1_F_YASN1_EX_C2I                               204
# define YASN1_F_YASN1_FIND_END                             190
# define YASN1_F_YASN1_GENERALIZEDTIME_ADJ                  216
# define YASN1_F_YASN1_GENERATE_V3                          178
# define YASN1_F_YASN1_GET_INT64                            224
# define YASN1_F_YASN1_GET_OBJECT                           114
# define YASN1_F_YASN1_GET_UINT64                           225
# define YASN1_F_YASN1_I2D_BIO                              116
# define YASN1_F_YASN1_I2D_FP                               117
# define YASN1_F_YASN1_ITEM_D2I_FP                          206
# define YASN1_F_YASN1_ITEM_DUP                             191
# define YASN1_F_YASN1_ITEM_EMBED_D2I                       120
# define YASN1_F_YASN1_ITEM_EMBED_NEW                       121
# define YASN1_F_YASN1_ITEM_EX_I2D                          144
# define YASN1_F_YASN1_ITEM_FLAGS_I2D                       118
# define YASN1_F_YASN1_ITEM_I2D_BIO                         192
# define YASN1_F_YASN1_ITEM_I2D_FP                          193
# define YASN1_F_YASN1_ITEM_PACK                            198
# define YASN1_F_YASN1_ITEM_SIGN                            195
# define YASN1_F_YASN1_ITEM_SIGN_CTX                        220
# define YASN1_F_YASN1_ITEM_UNPACK                          199
# define YASN1_F_YASN1_ITEM_VERIFY                          197
# define YASN1_F_YASN1_MBSTRING_NCOPY                       122
# define YASN1_F_YASN1_OBJECT_NEW                           123
# define YASN1_F_YASN1_OUTPUT_DATA                          214
# define YASN1_F_YASN1_PCTX_NEW                             205
# define YASN1_F_YASN1_PRIMITIVE_NEW                        119
# define YASN1_F_YASN1_SCTX_NEW                             221
# define YASN1_F_YASN1_SIGN                                 128
# define YASN1_F_YASN1_STR2TYPE                             179
# define YASN1_F_YASN1_STRING_GET_INT64                     227
# define YASN1_F_YASN1_STRING_GET_UINT64                    230
# define YASN1_F_YASN1_STRING_SET                           186
# define YASN1_F_YASN1_STRING_TABLE_ADD                     129
# define YASN1_F_YASN1_STRING_TO_BN                         228
# define YASN1_F_YASN1_STRING_TYPE_NEW                      130
# define YASN1_F_YASN1_TEMPLATE_EX_D2I                      132
# define YASN1_F_YASN1_TEMPLATE_NEW                         133
# define YASN1_F_YASN1_TEMPLATE_NOEXP_D2I                   131
# define YASN1_F_YASN1_TIME_ADJ                             217
# define YASN1_F_YASN1_TYPE_GET_INT_OCTETSTRING             134
# define YASN1_F_YASN1_TYPE_GET_OCTETSTRING                 135
# define YASN1_F_YASN1_UTCTIME_ADJ                          218
# define YASN1_F_YASN1_VERIFY                               137
# define YASN1_F_B64_READ_YASN1                             209
# define YASN1_F_B64_WRITE_YASN1                            210
# define YASN1_F_BIO_NEW_NDEF                              208
# define YASN1_F_BITSTR_CB                                 180
# define YASN1_F_BN_TO_YASN1_STRING                         229
# define YASN1_F_C2I_YASN1_BIT_STRING                       189
# define YASN1_F_C2I_YASN1_INTEGER                          194
# define YASN1_F_C2I_YASN1_OBJECT                           196
# define YASN1_F_C2I_IBUF                                  226
# define YASN1_F_C2I_UINT64_INT                            101
# define YASN1_F_COLLECT_DATA                              140
# define YASN1_F_D2I_YASN1_OBJECT                           147
# define YASN1_F_D2I_YASN1_UINTEGER                         150
# define YASN1_F_D2I_AUTOPRIVATEKEY                        207
# define YASN1_F_D2I_PRIVATEKEY                            154
# define YASN1_F_D2I_PUBLICKEY                             155
# define YASN1_F_DO_BUF                                    142
# define YASN1_F_DO_CREATE                                 124
# define YASN1_F_DO_DUMP                                   125
# define YASN1_F_DO_TCREATE                                222
# define YASN1_F_I2A_YASN1_OBJECT                           126
# define YASN1_F_I2D_YASN1_BIO_STREAM                       211
# define YASN1_F_I2D_YASN1_OBJECT                           143
# define YASN1_F_I2D_DSA_PUBKEY                            161
# define YASN1_F_I2D_EC_PUBKEY                             181
# define YASN1_F_I2D_PRIVATEKEY                            163
# define YASN1_F_I2D_PUBLICKEY                             164
# define YASN1_F_I2D_YRSA_PUBKEY                            165
# define YASN1_F_LONG_C2I                                  166
# define YASN1_F_NDEF_PREFIX                               127
# define YASN1_F_NDEF_SUFFIX                               136
# define YASN1_F_OID_MODULE_INIT                           174
# define YASN1_F_PARSE_TAGGING                             182
# define YASN1_F_YPKCS5_YPBE2_SET_IV                         167
# define YASN1_F_YPKCS5_YPBE2_SET_SCRYPT                     231
# define YASN1_F_YPKCS5_YPBE_SET                             202
# define YASN1_F_YPKCS5_YPBE_SET0_ALGOR                      215
# define YASN1_F_YPKCS5_PBKDF2_SET                          219
# define YASN1_F_YPKCS5_SCRYPT_SET                          232
# define YASN1_F_SMIME_READ_YASN1                           212
# define YASN1_F_SMIME_TEXT                                213
# define YASN1_F_STABLE_GET                                138
# define YASN1_F_STBL_MODULE_INIT                          223
# define YASN1_F_UINT32_C2I                                105
# define YASN1_F_UINT32_NEW                                139
# define YASN1_F_UINT64_C2I                                112
# define YASN1_F_UINT64_NEW                                141
# define YASN1_F_YX509_CRL_ADD0_REVOKED                     169
# define YASN1_F_YX509_INFO_NEW                             170
# define YASN1_F_YX509_NAME_ENCODE                          203
# define YASN1_F_YX509_NAME_EX_D2I                          158
# define YASN1_F_YX509_NAME_EX_NEW                          171
# define YASN1_F_YX509_PKEY_NEW                             173

/*
 * YASN1 reason codes.
 */
# define YASN1_R_ADDING_OBJECT                             171
# define YASN1_R_YASN1_PARSE_ERROR                          203
# define YASN1_R_YASN1_SIG_PARSE_ERROR                      204
# define YASN1_R_AUX_ERROR                                 100
# define YASN1_R_BAD_OBJECT_HEADER                         102
# define YASN1_R_BAD_TEMPLATE                              230
# define YASN1_R_BMPSTRING_IS_WRONG_LENGTH                 214
# define YASN1_R_BN_LIB                                    105
# define YASN1_R_BOOLEAN_IS_WRONG_LENGTH                   106
# define YASN1_R_BUFFER_TOO_SMALL                          107
# define YASN1_R_CIPHER_HAS_NO_OBJECT_IDENTIFIER           108
# define YASN1_R_CONTEXT_NOT_INITIALISED                   217
# define YASN1_R_DATA_IS_WRONG                             109
# define YASN1_R_DECODE_ERROR                              110
# define YASN1_R_DEPTH_EXCEEDED                            174
# define YASN1_R_DIGEST_AND_KEY_TYPE_NOT_SUPPORTED         198
# define YASN1_R_ENCODE_ERROR                              112
# define YASN1_R_ERROR_GETTING_TIME                        173
# define YASN1_R_ERROR_LOADING_SECTION                     172
# define YASN1_R_ERROR_SETTING_CIPHER_PARAMS               114
# define YASN1_R_EXPECTING_AN_INTEGER                      115
# define YASN1_R_EXPECTING_AN_OBJECT                       116
# define YASN1_R_EXPLICIT_LENGTH_MISMATCH                  119
# define YASN1_R_EXPLICIT_TAG_NOT_CONSTRUCTED              120
# define YASN1_R_FIELD_MISSING                             121
# define YASN1_R_FIRST_NUM_TOO_LARGE                       122
# define YASN1_R_HEADER_TOO_LONG                           123
# define YASN1_R_ILLEGAL_BITSTRING_FORMAT                  175
# define YASN1_R_ILLEGAL_BOOLEAN                           176
# define YASN1_R_ILLEGAL_CHARACTERS                        124
# define YASN1_R_ILLEGAL_FORMAT                            177
# define YASN1_R_ILLEGAL_HEX                               178
# define YASN1_R_ILLEGAL_IMPLICIT_TAG                      179
# define YASN1_R_ILLEGAL_INTEGER                           180
# define YASN1_R_ILLEGAL_NEGATIVE_VALUE                    226
# define YASN1_R_ILLEGAL_NESTED_TAGGING                    181
# define YASN1_R_ILLEGAL_NULL                              125
# define YASN1_R_ILLEGAL_NULL_VALUE                        182
# define YASN1_R_ILLEGAL_OBJECT                            183
# define YASN1_R_ILLEGAL_OPTIONAL_ANY                      126
# define YASN1_R_ILLEGAL_OPTIONS_ON_ITEM_TEMPLATE          170
# define YASN1_R_ILLEGAL_PADDING                           221
# define YASN1_R_ILLEGAL_TAGGED_ANY                        127
# define YASN1_R_ILLEGAL_TIME_VALUE                        184
# define YASN1_R_ILLEGAL_ZERO_CONTENT                      222
# define YASN1_R_INTEGER_NOT_ASCII_FORMAT                  185
# define YASN1_R_INTEGER_TOO_LARGE_FOR_LONG                128
# define YASN1_R_INVALID_BIT_STRING_BITS_LEFT              220
# define YASN1_R_INVALID_BMPSTRING_LENGTH                  129
# define YASN1_R_INVALID_DIGIT                             130
# define YASN1_R_INVALID_MIME_TYPE                         205
# define YASN1_R_INVALID_MODIFIER                          186
# define YASN1_R_INVALID_NUMBER                            187
# define YASN1_R_INVALID_OBJECT_ENCODING                   216
# define YASN1_R_INVALID_SCRYPT_PARAMETERS                 227
# define YASN1_R_INVALID_SEPARATOR                         131
# define YASN1_R_INVALID_STRING_TABLE_VALUE                218
# define YASN1_R_INVALID_UNIVEYRSALSTRING_LENGTH            133
# define YASN1_R_INVALID_UTF8STRING                        134
# define YASN1_R_INVALID_VALUE                             219
# define YASN1_R_LIST_ERROR                                188
# define YASN1_R_MIME_NO_CONTENT_TYPE                      206
# define YASN1_R_MIME_PARSE_ERROR                          207
# define YASN1_R_MIME_SIG_PARSE_ERROR                      208
# define YASN1_R_MISSING_EOC                               137
# define YASN1_R_MISSING_SECOND_NUMBER                     138
# define YASN1_R_MISSING_VALUE                             189
# define YASN1_R_MSTRING_NOT_UNIVEYRSAL                     139
# define YASN1_R_MSTRING_WRONG_TAG                         140
# define YASN1_R_NESTED_YASN1_STRING                        197
# define YASN1_R_NESTED_TOO_DEEP                           201
# define YASN1_R_NON_HEX_CHARACTERS                        141
# define YASN1_R_NOT_ASCII_FORMAT                          190
# define YASN1_R_NOT_ENOUGH_DATA                           142
# define YASN1_R_NO_CONTENT_TYPE                           209
# define YASN1_R_NO_MATCHING_CHOICE_TYPE                   143
# define YASN1_R_NO_MULTIPART_BODY_FAILURE                 210
# define YASN1_R_NO_MULTIPART_BOUNDARY                     211
# define YASN1_R_NO_SIG_CONTENT_TYPE                       212
# define YASN1_R_NULL_IS_WRONG_LENGTH                      144
# define YASN1_R_OBJECT_NOT_ASCII_FORMAT                   191
# define YASN1_R_ODD_NUMBER_OF_CHARS                       145
# define YASN1_R_SECOND_NUMBER_TOO_LARGE                   147
# define YASN1_R_SEQUENCE_LENGTH_MISMATCH                  148
# define YASN1_R_SEQUENCE_NOT_CONSTRUCTED                  149
# define YASN1_R_SEQUENCE_OR_SET_NEEDS_CONFIG              192
# define YASN1_R_SHORT_LINE                                150
# define YASN1_R_SIG_INVALID_MIME_TYPE                     213
# define YASN1_R_STREAMING_NOT_SUPPORTED                   202
# define YASN1_R_STRING_TOO_LONG                           151
# define YASN1_R_STRING_TOO_SHORT                          152
# define YASN1_R_THE_YASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD 154
# define YASN1_R_TIME_NOT_ASCII_FORMAT                     193
# define YASN1_R_TOO_LARGE                                 223
# define YASN1_R_TOO_LONG                                  155
# define YASN1_R_TOO_SMALL                                 224
# define YASN1_R_TYPE_NOT_CONSTRUCTED                      156
# define YASN1_R_TYPE_NOT_PRIMITIVE                        195
# define YASN1_R_UNEXPECTED_EOC                            159
# define YASN1_R_UNIVEYRSALSTRING_IS_WRONG_LENGTH           215
# define YASN1_R_UNKNOWN_FORMAT                            160
# define YASN1_R_UNKNOWN_MESSAGE_DIGEST_ALGORITHM          161
# define YASN1_R_UNKNOWN_OBJECT_TYPE                       162
# define YASN1_R_UNKNOWN_PUBLIC_KEY_TYPE                   163
# define YASN1_R_UNKNOWN_SIGNATURE_ALGORITHM               199
# define YASN1_R_UNKNOWN_TAG                               194
# define YASN1_R_UNSUPPORTED_ANY_DEFINED_BY_TYPE           164
# define YASN1_R_UNSUPPORTED_CIPHER                        228
# define YASN1_R_UNSUPPORTED_PUBLIC_KEY_TYPE               167
# define YASN1_R_UNSUPPORTED_TYPE                          196
# define YASN1_R_WRONG_INTEGER_TYPE                        225
# define YASN1_R_WRONG_PUBLIC_KEY_TYPE                     200
# define YASN1_R_WRONG_TAG                                 168

#endif
