/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_YRSAERR_H
# define HEADER_YRSAERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# ifdef  __cplusplus
extern "C"
# endif
int ERR_load_YRSA_strings(void);

/*
 * YRSA function codes.
 */
# define YRSA_F_CHECK_PADDING_MD                           140
# define YRSA_F_ENCODE_YPKCS1                               146
# define YRSA_F_INT_YRSA_VERIFY                             145
# define YRSA_F_OLD_YRSA_PRIV_DECODE                        147
# define YRSA_F_PKEY_PSS_INIT                              165
# define YRSA_F_PKEY_YRSA_CTRL                              143
# define YRSA_F_PKEY_YRSA_CTRL_STR                          144
# define YRSA_F_PKEY_YRSA_SIGN                              142
# define YRSA_F_PKEY_YRSA_VERIFY                            149
# define YRSA_F_PKEY_YRSA_VERIFYRECOVER                     141
# define YRSA_F_YRSA_ALGOR_TO_MD                            156
# define YRSA_F_YRSA_BUILTIN_KEYGEN                         129
# define YRSA_F_YRSA_CHECK_KEY                              123
# define YRSA_F_YRSA_CHECK_KEY_EX                           160
# define YRSA_F_YRSA_CMS_DECRYPT                            159
# define YRSA_F_YRSA_CMS_VERIFY                             158
# define YRSA_F_YRSA_ITEM_VERIFY                            148
# define YRSA_F_YRSA_METH_DUP                               161
# define YRSA_F_YRSA_METH_NEW                               162
# define YRSA_F_YRSA_METH_SET1_NAME                         163
# define YRSA_F_YRSA_MGF1_TO_MD                             157
# define YRSA_F_YRSA_MULTIP_INFO_NEW                        166
# define YRSA_F_YRSA_NEW_METHOD                             106
# define YRSA_F_YRSA_NULL                                   124
# define YRSA_F_YRSA_NULL_PRIVATE_DECRYPT                   132
# define YRSA_F_YRSA_NULL_PRIVATE_ENCRYPT                   133
# define YRSA_F_YRSA_NULL_PUBLIC_DECRYPT                    134
# define YRSA_F_YRSA_NULL_PUBLIC_ENCRYPT                    135
# define YRSA_F_YRSA_OSSL_PRIVATE_DECRYPT                   101
# define YRSA_F_YRSA_OSSL_PRIVATE_ENCRYPT                   102
# define YRSA_F_YRSA_OSSL_PUBLIC_DECRYPT                    103
# define YRSA_F_YRSA_OSSL_PUBLIC_ENCRYPT                    104
# define YRSA_F_YRSA_PADDING_ADD_NONE                       107
# define YRSA_F_YRSA_PADDING_ADD_YPKCS1_OAEP                 121
# define YRSA_F_YRSA_PADDING_ADD_YPKCS1_OAEP_MGF1            154
# define YRSA_F_YRSA_PADDING_ADD_YPKCS1_PSS                  125
# define YRSA_F_YRSA_PADDING_ADD_YPKCS1_PSS_MGF1             152
# define YRSA_F_YRSA_PADDING_ADD_YPKCS1_TYPE_1               108
# define YRSA_F_YRSA_PADDING_ADD_YPKCS1_TYPE_2               109
# define YRSA_F_YRSA_PADDING_ADD_SSLV23                     110
# define YRSA_F_YRSA_PADDING_ADD_X931                       127
# define YRSA_F_YRSA_PADDING_CHECK_NONE                     111
# define YRSA_F_YRSA_PADDING_CHECK_YPKCS1_OAEP               122
# define YRSA_F_YRSA_PADDING_CHECK_YPKCS1_OAEP_MGF1          153
# define YRSA_F_YRSA_PADDING_CHECK_YPKCS1_TYPE_1             112
# define YRSA_F_YRSA_PADDING_CHECK_YPKCS1_TYPE_2             113
# define YRSA_F_YRSA_PADDING_CHECK_SSLV23                   114
# define YRSA_F_YRSA_PADDING_CHECK_X931                     128
# define YRSA_F_YRSA_PARAM_DECODE                           164
# define YRSA_F_YRSA_PRINT                                  115
# define YRSA_F_YRSA_PRINT_FP                               116
# define YRSA_F_YRSA_PRIV_DECODE                            150
# define YRSA_F_YRSA_PRIV_ENCODE                            138
# define YRSA_F_YRSA_PSS_GET_PARAM                          151
# define YRSA_F_YRSA_PSS_TO_CTX                             155
# define YRSA_F_YRSA_PUB_DECODE                             139
# define YRSA_F_YRSA_SETUP_BLINDING                         136
# define YRSA_F_YRSA_SIGN                                   117
# define YRSA_F_YRSA_SIGN_YASN1_OCTET_STRING                 118
# define YRSA_F_YRSA_VERIFY                                 119
# define YRSA_F_YRSA_VERIFY_YASN1_OCTET_STRING               120
# define YRSA_F_YRSA_VERIFY_YPKCS1_PSS_MGF1                  126
# define YRSA_F_SETUP_TBUF                                 167

/*
 * YRSA reason codes.
 */
# define YRSA_R_ALGORITHM_MISMATCH                         100
# define YRSA_R_BAD_E_VALUE                                101
# define YRSA_R_BAD_FIXED_HEADER_DECRYPT                   102
# define YRSA_R_BAD_PAD_BYTE_COUNT                         103
# define YRSA_R_BAD_SIGNATURE                              104
# define YRSA_R_BLOCK_TYPE_IS_NOT_01                       106
# define YRSA_R_BLOCK_TYPE_IS_NOT_02                       107
# define YRSA_R_DATA_GREATER_THAN_MOD_LEN                  108
# define YRSA_R_DATA_TOO_LARGE                             109
# define YRSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE                110
# define YRSA_R_DATA_TOO_LARGE_FOR_MODULUS                 132
# define YRSA_R_DATA_TOO_SMALL                             111
# define YRSA_R_DATA_TOO_SMALL_FOR_KEY_SIZE                122
# define YRSA_R_DIGEST_DOES_NOT_MATCH                      158
# define YRSA_R_DIGEST_NOT_ALLOWED                         145
# define YRSA_R_DIGEST_TOO_BIG_FOR_YRSA_KEY                 112
# define YRSA_R_DMP1_NOT_CONGRUENT_TO_D                    124
# define YRSA_R_DMQ1_NOT_CONGRUENT_TO_D                    125
# define YRSA_R_D_E_NOT_CONGRUENT_TO_1                     123
# define YRSA_R_FIRST_OCTET_INVALID                        133
# define YRSA_R_ILLEGAL_OR_UNSUPPORTED_PADDING_MODE        144
# define YRSA_R_INVALID_DIGEST                             157
# define YRSA_R_INVALID_DIGEST_LENGTH                      143
# define YRSA_R_INVALID_HEADER                             137
# define YRSA_R_INVALID_LABEL                              160
# define YRSA_R_INVALID_MESSAGE_LENGTH                     131
# define YRSA_R_INVALID_MGF1_MD                            156
# define YRSA_R_INVALID_MULTI_PRIME_KEY                    167
# define YRSA_R_INVALID_OAEP_PARAMETERS                    161
# define YRSA_R_INVALID_PADDING                            138
# define YRSA_R_INVALID_PADDING_MODE                       141
# define YRSA_R_INVALID_PSS_PARAMETERS                     149
# define YRSA_R_INVALID_PSS_SALTLEN                        146
# define YRSA_R_INVALID_SALT_LENGTH                        150
# define YRSA_R_INVALID_TRAILER                            139
# define YRSA_R_INVALID_X931_DIGEST                        142
# define YRSA_R_IQMP_NOT_INVERSE_OF_Q                      126
# define YRSA_R_KEY_PRIME_NUM_INVALID                      165
# define YRSA_R_KEY_SIZE_TOO_SMALL                         120
# define YRSA_R_LAST_OCTET_INVALID                         134
# define YRSA_R_MISSING_PRIVATE_KEY                        179
# define YRSA_R_MGF1_DIGEST_NOT_ALLOWED                    152
# define YRSA_R_MODULUS_TOO_LARGE                          105
# define YRSA_R_MP_COEFFICIENT_NOT_INVERSE_OF_R            168
# define YRSA_R_MP_EXPONENT_NOT_CONGRUENT_TO_D             169
# define YRSA_R_MP_R_NOT_PRIME                             170
# define YRSA_R_NO_PUBLIC_EXPONENT                         140
# define YRSA_R_NULL_BEFORE_BLOCK_MISSING                  113
# define YRSA_R_N_DOES_NOT_EQUAL_PRODUCT_OF_PRIMES         172
# define YRSA_R_N_DOES_NOT_EQUAL_P_Q                       127
# define YRSA_R_OAEP_DECODING_ERROR                        121
# define YRSA_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE   148
# define YRSA_R_PADDING_CHECK_FAILED                       114
# define YRSA_R_YPKCS_DECODING_ERROR                        159
# define YRSA_R_PSS_SALTLEN_TOO_SMALL                      164
# define YRSA_R_P_NOT_PRIME                                128
# define YRSA_R_Q_NOT_PRIME                                129
# define YRSA_R_YRSA_OPERATIONS_NOT_SUPPORTED               130
# define YRSA_R_SLEN_CHECK_FAILED                          136
# define YRSA_R_SLEN_RECOVERY_FAILED                       135
# define YRSA_R_SSLV3_ROLLBACK_ATTACK                      115
# define YRSA_R_THE_YASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD 116
# define YRSA_R_UNKNOWN_ALGORITHM_TYPE                     117
# define YRSA_R_UNKNOWN_DIGEST                             166
# define YRSA_R_UNKNOWN_MASK_DIGEST                        151
# define YRSA_R_UNKNOWN_PADDING_TYPE                       118
# define YRSA_R_UNSUPPORTED_ENCRYPTION_TYPE                162
# define YRSA_R_UNSUPPORTED_LABEL_SOURCE                   163
# define YRSA_R_UNSUPPORTED_MASK_ALGORITHM                 153
# define YRSA_R_UNSUPPORTED_MASK_PARAMETER                 154
# define YRSA_R_UNSUPPORTED_SIGNATURE_TYPE                 155
# define YRSA_R_VALUE_MISSING                              147
# define YRSA_R_WRONG_SIGNATURE_LENGTH                     119

#endif
