/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: darwin64-arm64-cc"
#define DATE "built on: Sun Mar 24 17:37:23 2024 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','/','A','p','p','l','i',
    'c','a','t','i','o','n','s','/','X','c','o','d','e','.','a','p',
    'p','/','C','o','n','t','e','n','t','s','/','D','e','v','e','l',
    'o','p','e','r','/','T','o','o','l','c','h','a','i','n','s','/',
    'X','c','o','d','e','D','e','f','a','u','l','t','.','x','c','t',
    'o','o','l','c','h','a','i','n','/','u','s','r','/','b','i','n',
    '/','c','l','a','n','g',' ','-','f','P','I','C',' ','-','a','r',
    'c','h',' ','a','r','m','6','4',' ','-','O','3',' ','-','W','a',
    'l','l',' ','-','-','t','a','r','g','e','t','=','a','r','m','6',
    '4','-','a','p','p','l','e','-','d','a','r','w','i','n','2','1',
    '.','5','.','0',' ','-','D','L','_','E','N','D','I','A','N',' ',
    '-','D','O','P','E','N','S','S','L','_','P','I','C',' ','-','D',
    'O','P','E','N','S','S','L','_','C','P','U','I','D','_','O','B',
    'J',' ','-','D','O','P','E','N','S','S','L','_','B','N','_','A',
    'S','M','_','M','O','N','T',' ','-','D','Y','S','H','A','1','_',
    'A','S','M',' ','-','D','Y','S','H','A','2','5','6','_','A','S',
    'M',' ','-','D','Y','S','H','A','5','1','2','_','A','S','M',' ',
    '-','D','K','E','C','C','A','K','1','6','0','0','_','A','S','M',
    ' ','-','D','V','P','Y','A','E','S','_','A','S','M',' ','-','D',
    'E','C','P','_','N','I','S','T','Z','2','5','6','_','A','S','M',
    ' ','-','D','P','O','L','Y','1','3','0','5','_','A','S','M',' ',
    '-','D','_','R','E','E','N','T','R','A','N','T',' ','-','D','N',
    'D','E','B','U','G','\0'
};
